name: Metrics
run-name: Updating ${{ github.event.repository.name }} metrics
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: "metrics"
  cancel-in-progress: true
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
    
      - name: Languages Metrics
        uses: Backist/Metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          #repo:
          #committer_token:
          #committer_branch:
          #committer_message:
          #committer_gist:
          filename: languages.*
          #markdown:
          #markdown_cache:
          output_action: none
          output_condition: data-changed
          optimize: css, xml, svg
          #setup_community_templates:
          #template:
          #query:
          #extras_css:
          #extras_js:
          #github_api_rest:
          #github_api_graphql:
          config_timezone: Europe/Madrid
          #config_order:
          #config_twemoji:
          config_gemoji: yes
          #config_octicon:
          config_display: regular
          config_animations: yes
          config_base64: yes
          #config_padding:
          config_output: auto
          #config_presets:
          retries: 5
          retries_delay: 600
          retries_output_action: 5
          retries_delay_output_action: 300
          clean_workflows: failure
          #delay:
          #quota_required_rest:
          #quota_required_graphql:
          #quota_required_search:
          notice_releases: yes
          use_prebuilt_image: yes
          #plugins_errors_fatal:
          debug: no
          verify: no
          #debug_flags:
          #debug_print:
          #dryrun:
          experimental_features: --optimize-svg
          #use_mocked_data
          base: ""
          plugin_languages: yes
          #plugin_languages_ignored:
          #plugin_languages_skipped:
          plugin_languages_limit: 0
          #plugin_languages_threshold:
          #plugin_languages_other:
          #plugin_languages_colors:
          #plugin_languages_aliases:
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_indepth: yes
          #plugin_languages_indepth_custom:
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          #plugin_languages_categories:
          #plugin_languages_recent_categories:
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
          
      - name: Habits Metrics
        uses: Backist/Metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          #repo:
          #committer_token:
          #committer_branch:
          #committer_message:
          #committer_gist:
          filename: habits.*
          #markdown:
          #markdown_cache:
          output_action: none
          output_condition: data-changed
          optimize: css, xml, svg
          #setup_community_templates:
          #template:
          #query:
          #extras_css:
          #extras_js:
          #github_api_rest:
          #github_api_graphql:
          config_timezone: Europe/Madrid
          #config_order:
          #config_twemoji:
          config_gemoji: yes
          #config_octicon:
          config_display: regular
          config_animations: yes
          config_base64: yes
          #config_padding:
          config_output: auto
          #config_presets:
          retries: 5
          retries_delay: 600
          retries_output_action: 5
          retries_delay_output_action: 300
          clean_workflows: failure
          #delay:
          #quota_required_rest:
          #quota_required_graphql:
          #quota_required_search:
          notice_releases: yes
          use_prebuilt_image: yes
          #plugins_errors_fatal:
          debug: no
          verify: no
          #debug_flags:
          #debug_print:
          #dryrun:
          experimental_features: --optimize-svg
          #use_mocked_data
          base: ""
          plugin_habits: yes
          plugin_habits_from: 1000
          #plugin_habits_skipped:
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: no
          #plugin_habits_charts_type:
          #plugin_habits_trim:
          plugin_habits_languages_limit: 0
          #plugin_habits_languages_threshold:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Flush Metrics
        shell: bash
        run: |
          rm -fr ./assets/metrics
          mkdir -p ./assets/metrics
          cp -f /metrics_renders/* ./assets/metrics
          
          echo "Flushed Metrics"

      - name: Update Repository
        shell: bash
        run: |
          git add .
          git commit -m "Metrics Update"
          git push
          
          echo "Updated Repository"
